## 14. Lambda Functions in Python

#### Q. What is Lambda Function?

A Lambda function is a small, anonymous(nameless) function written in one single line.

📌 Simple Define
> A Lambda function is a one-line function without a name.


### Why Lambda function are used?

### Why Lambda Functions are used?

* ꪜShort and clean code
* ꪜUsed for temporary operation
* ꪜCommon with map(), filter(), reduce(), sort(), apply()
* ꪜImprove readability in simple logic


### Normal Function VS Lambda Function

### Syntax
`(lambda variable:expression)(arguments)`

### Normal Function

In [1]:
def square(x):
    return x*x
square(10)

100

### Lambda Function

In [2]:
(lambda a:a*a)(10)

100

In [3]:
var = (lambda x:x*x)
var(10)

100

In [4]:
var(100)

10000

### Syntax of Lambda function

lambda arguments:expression

📌 Rules:
* ꪜCan have Multiple arguments
* ꪜOnly one expression
* ꪜAutomatically return result
* ꪜNo return keyword

##### Basic Examples

1. add two numbers

In [6]:
# lambda function
add = (lambda a,b:a+b)
add(10,12)

22

In [7]:
add(10,20)

30

In [8]:
add(50,14)

64

##### 2. Square of a number

In [9]:
square = (lambda x:x**2)
square(5)

25

In [10]:
(lambda x:x**2)(5)

25

### 3. check Even or Odd

##### Normal Function

In [14]:
def checkEven(x):
    if x%2==0:
        return "Even"

checkEven(10)

'Even'

In [16]:
evenNum = (lambda a: "Even"  if a%2==0 else "Odd" )
evenNum(10)

'Even'

In [17]:
evenNum(11)

'Odd'

##### Lambda with multiple arguments

Normal Function

In [19]:
def maxNum(a,b,c):
    if a>b and a>c:
        print(a)
    elif b>a and b>c:
        print(b)
    elif c>a and c>b:
        print(c)
maxNum(10,9,11)

11

In [20]:
max_num = (lambda a,b,c: a if a>b and a>c else (b if b>a and b>c else c))
max_num(10,9,11)

11

### Lambda Built-in Function()

1. filter()
2. map()
3. reduce()
4. sort()
5. apply()

### Lambda with Filter()

Filter elemnets based on condition

syntax:

`filter(function, sequence)`

In [21]:
numbers = [1,2,3,4,5,6,7,8,9,10]

# Normal Function

In [22]:
def evenNum(x):
    return x%2==0

evenNum(10)

True

In [25]:
# Normal
numbers = [1,2,3,4,5,6,7,8,9,10]
list(filter(evenNum,numbers))

[2, 4, 6, 8, 10]

In [27]:
# anonymous 
numbers = [1,2,3,4,5,6,7,8,9,10]
list(filter(lambda a: a%2==0,numbers))

[2, 4, 6, 8, 10]

In [32]:
# Odd Numbers 
numbers = [1,2,3,4,5,6,7,8,9,10]

def oddNum(x):
    return x%2!=0

list(filter(oddNum,numbers))

[1, 3, 5, 7, 9]

In [33]:
list(filter(lambda a:a%2!=0,numbers))

[1, 3, 5, 7, 9]

### 2. Lambda with map()

Purpose: Apply a function to each elements in a list.

In [28]:
numbers = [1,2,3,4,5,6,7,8,9,10]

# Normal 

def sqrNum(x):
    return x**2

In [31]:
numbers = [1,2,3,4,5,6,7,8,9,10]
list(map(sqrNum, numbers))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [34]:
list(map(lambda a:a**2,numbers))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### 3. Lambda with reduce()

Module: functools

`from functools import reduce`

In [37]:
from functools import reduce

In [41]:
numbers = [1,2,3,4,5,6,7,8,9,10]


def sumValue(x,y):
    return x+y

reduce(sumValue, numbers)

55

In [40]:
reduce(lambda a,b:a+b, numbers)

55

### 4. Lambda with sort()

In [42]:
students = [("Ram",89),("Anita",66),("Kiran",10)]

sorted(students,key=lambda x:x[0])

[('Anita', 66), ('Kiran', 10), ('Ram', 89)]

In [43]:
sorted(students,key=lambda x:x[1])

[('Kiran', 10), ('Anita', 66), ('Ram', 89)]

In [44]:
sorted(students,key=lambda x:x[2])

IndexError: tuple index out of range

#### When Not use lambda 

* ❌ Complex Logic
* ❌ Multiple Conditions
* ❌ Multiple Lines
* ❌ Resusable business logic

##### 📌 Used def instead
---

One-Liner about lambda 

* ꪜLambda is an anonymous function
* ꪜWritten in one line
* ꪜNo return keyword
* ꪜUsed with map(), reduce(), filter(), sorted(), apply()
* ꪜImport code readability for small task

##### Summary
> Lambda function are small, one-line, nameless function used for sort operations.

### 5. lambda with Apply()

Q. What is apply()?

apply() is used in Pandas to apply a function(including lambda) to:
* Each column
* Each row
* Each cell(Series)

##### Simple Define
> apply() applies a funciton to data elements

----

##### Why Use Lambda with apply()?

* ꪜShort, clean logic
* ꪜNo need to define full function.
* ꪜBest for data transformation
* ꪜWidely used in Data Science

----

##### Required Library

`import pandas as pd`


Lambda with apply on a Series

In [45]:
import pandas as pd

In [46]:
data = [1,2,3,4,5,6,7,8,9,10]

print(data, type(data))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>

In [47]:
df = pd.Series(data)
df

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [48]:
df = pd.DataFrame(data)
df

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [53]:
data = [1,2,3,4,5,6,7,8,9,10]

print(data, type(data))

sqrNum = []
for i in data:
    # print(i**2)
    sqr = i**2
    sqrNum.append(sqr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>

In [54]:
dataSeries = pd.Series(sqrNum)
print(dataSeries)

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int64

In [55]:
data = [1,2,3,4,5,6,7,8,9,10]

print(data, type(data))

df = pd.DataFrame(data)
df

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [56]:
df['Square']=df.apply(lambda x:x**2)

In [57]:
df

    0  Square
0   1       1
1   2       4
2   3       9
3   4      16
4   5      25
5   6      36
6   7      49
7   8      64
8   9      81
9  10     100

### 2. Lambda with apply() DataFrame Column

Example: Increate salary by 10%

In [58]:
data = {
    "Name":["Ram","Anita","Kiran"],
    "Salary":[40000,50000,45000]
}
df = pd.DataFrame(data)
df

    Name  Salary
0    Ram   40000
1  Anita   50000
2  Kiran   45000

In [60]:
df["10% Increase"] = df['Salary'].apply(lambda x: ((x*1/10)))
df

    Name  Salary  10% Increase
0    Ram   40000        4000.0
1  Anita   50000        5000.0
2  Kiran   45000        4500.0

In [61]:
# Total Salary

df["Total Salary"] = df['Salary']+df['10% Increase']
df

    Name  Salary  10% Increase  Total Salary
0    Ram   40000        4000.0       44000.0
1  Anita   50000        5000.0       55000.0
2  Kiran   45000        4500.0       49500.0

In [62]:
df["Total Salary 2"] = df['Salary'].apply(lambda x:x+ ((x*1/10)))
df

    Name  Salary  10% Increase  Total Salary  Total Salary 2
0    Ram   40000        4000.0       44000.0         44000.0
1  Anita   50000        5000.0       55000.0         55000.0
2  Kiran   45000        4500.0       49500.0         49500.0